import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(readFileSync(path,'utf8')).toString('base64'));
const {ServerClock,cueSource,bubbleFromEvent}=await load(new URL('../lantern_hollow/web/presentation.js',import.meta.url));
const {BubbleQueue}=await load(process.argv[2]);
let mono=0;const clock=new ServerClock(()=>mono,100);
mono=2;assert.equal(clock.now(),102);
const realDateNow=Date.now;Date.now=()=>realDateNow()+3600000;
mono=3;assert.equal(clock.now(),103);Date.now=()=>1;
mono=4;assert.equal(clock.now(),104);Date.now=realDateNow;
clock.sync(200);mono=5;assert.equal(clock.now(),201);
assert.equal(clock.sync(NaN),false);assert.equal(clock.now(),201);
const event={event_id:'one',kind:'world.presentation',historical:false,payload:{name:'public_expression',channel:'speech',phase:'start',subject_id:'a',data:{text:'<script>not HTML</script>',at:100,expires_at:108}}};
assert.equal(cueSource(event.payload),'authored');
const message=bubbleFromEvent(event);assert.equal(message.text,event.payload.data.text);
assert.equal(bubbleFromEvent({...event,historical:true}),null);
assert.equal(bubbleFromEvent({...event,payload:{...event.payload,data:{text:'missing time'}}}),null);
assert.equal(cueSource({name:'dialogue'}),'scripted');
assert.equal(cueSource({name:'walk'}),'system');
const queue=new BubbleQueue();queue.push(message,100);queue.push({...message,id:'two'},100);
assert.equal(queue.active(100)[0].source,'authored');
assert.equal(queue.active(110).length,0);
assert.equal(queue.push({...message,id:'already-expired'},110),false);
console.log('presentation: monotonic clock, source attribution, history boundary, absolute expiry PASS');
