"""Keyboard, named surfaces and test-time artwork replacement; no world mutations by assets."""
from pathlib import Path
import argparse,json,sys,hashlib,base64
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from tests.live import LiveServer
from tools.frontend_test_support import launch_browser,static_client

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--axe',required=True);parser.add_argument('--output',default='test-results/accessibility-gate');args=parser.parse_args();out=ROOT/args.output;out.mkdir(parents=True,exist_ok=True);reports={};errors=[];cases={};axe=Path(args.axe).read_text(encoding='utf-8')
 with static_client(ROOT/'examples/protocol-client') as other,LiveServer(observer_origins=(other,)) as server,sync_playwright() as p:
  browser=launch_browser(p);ctx=browser.new_context(viewport={'width':1280,'height':900},reduced_motion='reduce');page=ctx.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto(server.url+'/watch');expect(page.locator('#asset-status')).to_have_attribute('data-state','ready')
  def audit(name,pg=page):
   pg.evaluate(axe);result=pg.evaluate('async()=>{const r=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return {violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary,checks:[...n.any,...n.all,...n.none].map(c=>({id:c.id,message:c.message,data:c.data}))}))}))}}');result['manualStyles']=pg.evaluate('(targets)=>targets.map(target=>{const e=document.querySelector(target[0]);if(!e)return {target};const c=getComputedStyle(e);return {target,color:c.color,background:c.backgroundColor,fontSize:c.fontSize,role:e.getAttribute("role"),text:e.textContent.slice(0,120)}})',[n['target'] for rule in result['incomplete'] for n in rule['nodes']]);reports[name]=result;pg.screenshot(path=str(out/(name+'-audit.png')),full_page=True);(out/'axe.json').write_text(json.dumps(reports,ensure_ascii=False,indent=2),encoding='utf-8')
  def tab_to(identifier):
   for _ in range(80):
    if page.evaluate('document.activeElement.id')==identifier:return
    page.keyboard.press('Tab')
   raise AssertionError('Keyboard cannot reach '+identifier)
  audit('watch');tab_to('join-mode');page.keyboard.press('Enter');expect(page.locator('#name')).to_be_focused();audit('entry');page.keyboard.insert_text('Keyboard traveler');page.keyboard.press('Tab');page.keyboard.press('Enter');expect(page.locator('#say')).to_be_enabled();cases['join_keyboard_only']=True
  audit('player');tab_to('help');page.keyboard.press('Enter');audit('help');page.keyboard.press('Escape');expect(page.locator('#help')).to_be_focused();cases['dialog_focus_return']=True
  tab_to('say');page.keyboard.press('Enter');expect(page.locator('#modal textarea')).to_be_focused();page.keyboard.insert_text('Keyboard message wasd e');audit('composer');page.keyboard.press('Tab');page.keyboard.press('Enter');expect(page.locator('#timeline')).to_contain_text('Keyboard message wasd e');cases['compose_keyboard_only']=True
  # A composition key routed to the canvas cannot become a world move.
  writes=[];page.on('request',lambda r:writes.append(r.url) if r.url.endswith('/play/action') else None);page.locator('#world').focus();page.locator('#world').dispatch_event('keydown',{'key':'w','isComposing':True,'bubbles':True});page.wait_for_timeout(500);assert not writes;cases['synthetic_ime_event_not_world_input']=True
  gallery=ctx.new_page();gallery.goto(server.url+'/static/art-gallery.html');expect(gallery.locator('#status')).to_have_attribute('data-state','ready');audit('gallery',gallery);gallery.close()
  remote=browser.new_context();other_page=remote.new_page();other_page.goto(other);other_page.fill('#origin',server.url);other_page.locator('#connect button').click();expect(other_page.locator('#health')).to_have_attribute('data-state','ready');audit('independent',other_page);remote.close()
  # Contact sheets inspect all frame bounds and visible pixels, not just one portrait.
  sheet=ctx.new_page();sheet.goto(server.url+'/static/art-gallery.html');expect(sheet.locator('#status')).to_have_attribute('data-state','ready')
  pack=sheet.request.get(server.url+'/static/sample-assets.json').json()
  sheets=sheet.evaluate("""async()=>{const m=await(await fetch('/static/sample-assets.json')).json(),image=await createImageBitmap(await(await fetch('/static/sample-atlas.png')).blob());const result=[];for(const kind of m.characters){const keys=Object.keys(m.frames).filter(k=>k.startsWith(kind+'/'));const c=document.createElement('canvas');c.width=768;c.height=8*112;const x=c.getContext('2d');x.fillStyle='#1c3437';x.fillRect(0,0,c.width,c.height);x.imageSmoothingEnabled=false;for(let i=0;i<keys.length;i++){const f=m.frames[keys[i]],px=i%12*64,py=Math.floor(i/12)*112;x.drawImage(image,f.x,f.y,f.w,f.h,px+8,py+6,f.w*2,f.h*2);x.fillStyle='#f1e1b8';x.font='8px monospace';x.fillText(keys[i].split('/').slice(1).join('/'),px+2,py+89);}result.push({kind,png:c.toDataURL('image/png').split(',')[1],frames:keys.length});}return result;}""")
  for item in sheets:(out/(item['kind']+'-sheet.png')).write_bytes(base64.b64decode(item['png']))
  cases['all_character_frame_contact_sheets']={i['kind']:i['frames'] for i in sheets};assert sum(i['frames'] for i in sheets)==384
  # Replace decorative bytes and matching manifest, keeping scene facts unchanged.
  replacement=sheet.evaluate("""async()=>{const image=await createImageBitmap(await(await fetch('/static/sample-atlas.png')).blob());const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d');x.drawImage(image,0,0);const d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4)if(d.data[i+3]){const r=d.data[i];d.data[i]=d.data[i+1];d.data[i+1]=r;}x.putImageData(d,0,0);return c.toDataURL('image/png').split(',')[1];}""")
  raw=base64.b64decode(replacement);new_manifest={**pack,'version':'fixture-palette-swap','sha256':hashlib.sha256(raw).hexdigest()};view=ctx.new_page();view.goto(server.url+'/watch');expect(view.locator('#asset-status')).to_have_attribute('data-state','ready');old=view.locator('#world').evaluate('(c)=>c.toDataURL()');public_before=view.request.get(server.url+'/watch/session').json()['view']['snapshot'];view.route('**/sample-assets.json',lambda rt:rt.fulfill(json=new_manifest));view.route('**/sample-atlas.png*',lambda rt:rt.fulfill(status=200,content_type='image/png',body=raw));view.reload();expect(view.locator('#asset-status')).to_have_attribute('data-state','ready');expect(view.locator('#asset-status')).to_have_attribute('title','fixture-palette-swap');new=view.locator('#world').evaluate('(c)=>c.toDataURL()');assert old!=new;public_after=view.request.get(server.url+'/watch/session').json()['view']['snapshot'];assert public_before['entities']==public_after['entities'];view.screenshot(path=str(out/'replacement.png'),full_page=True);cases['asset_replacement_changes_pixels_not_facts']=True;view.close();sheet.close()
  assert not errors;bad={k:v['violations'] for k,v in reports.items() if v['violations']};result={'status':'passed' if not bad else 'failed','cases':cases,'axe':reports,'page_errors':errors,'scope':'Automated axe + keyboard + synthetic composition. Not screen-reader certification, OS keyboard or physical-device testing.'};(out/'report.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps({'cases':cases,'violations':bad,'page_errors':errors},ensure_ascii=False),flush=True);ctx.close();browser.close();assert not bad,bad
if __name__=='__main__':main()
